name: RAG Experiment CI

on:
  push:
    branches: [ "master" ]

jobs:
  test-and-experiment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest experiments/tests/test_search.py

      - name: Run grid experiment (10 samples)
        run: python experiments/grid_run.py --k 3 5 --temp 0.2 0.5 --chunk 256 --sample 10

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: grid_results
          path: experiments/results/*.csv 